name: Build Padavan Final

on:
  workflow_dispatch:
    inputs:
      production:
        description: 型号
        default: "NETGEAR-BZV"
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y ncurses-dev libssl-dev liblzma-dev zip unzip bison flex gperf
        sudo apt install -y autoconf automake libtool-bin python3-docutils autopoint gettext

    - name: Clone clean source
      run: |
        git clone --depth=1 https://github.com/hanwckf/padavan-ng.git /opt/rt-n56u
        cd /opt/rt-n56u
        git pull

    - name: Build firmware
      run: |
        cd /opt/rt-n56u/trunk
        cp configs/templates/NETGEAR-BZV.config .config
        make clean
        make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: /opt/rt-n56u/trunk/images/*.trx
