# 注意：修改 default:    中的型号为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build NETGEAR-BZV Padavan-3.4

on:
  workflow_dispatch:
    inputs:
      production:
        description: 设置编译的固件型号,空格分隔.
        default: "NETGEAR-BZV"
        required: false
      release:
        description: "是否需要发布到Release? (不发布也可以到Artifacts下载)"
        default: 'yes'
        required: false
env:
  MHZ: 1100
  TNAME: ${{ github.event.inputs.production }}
  REPOSITORY_URL: https://github.com/xiaiohuan/Padavan-KVR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hendrikmuhs/ccache-action@main
      with:
          key: ${{ github.event.inputs.production }}-3.4
    - name: Prepare environment
      run: |
          sudo apt update
          sudo apt install -y libtool-bin gperf python3-docutils autopoint gettext ccache bison flex
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL /opt/rt-n56u
        cd /opt/rt-n56u/trunk
        sed -i '/cp -f/d' Makefile
    - name: Build Firmware
      run: |
        cd /opt/rt-n56u/trunk
        for m in $TNAME; do
        cp -f configs/templates/$m.config .config
        make clean
        make
        mv -f images/*.trx /opt/
        done
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: /opt/*.trx
